// DO NOT MODIFY THIS FILE: AUTOGENERATED BY iigen (v0.2.1)
import * as i0 from './about.js'
import * as i1 from './apply.js'
import * as i2 from './blog.js'
import * as i3 from './contact.js'
import * as i4 from './ecolodge.js'
import * as i5 from './event.js'
import * as i6 from './gallery.js'
import * as i7 from './home.js'
import * as i8 from './index.js'
import * as i9 from './location.js'
import * as i10 from './mission.js'
import * as i11 from './partners.js'
import * as i12 from './projects.js'
import * as i13 from './resources.js'
import * as i14 from './spreadtheword.js'
import * as i15 from './team.js'
import * as i16 from './trustees.js'
import * as i17 from './us.js'
import * as i18 from './volunteering.js'

export default [
  { filename: 'about.js', exported: i0 },
  { filename: 'apply.js', exported: i1 },
  { filename: 'blog.js', exported: i2 },
  { filename: 'contact.js', exported: i3 },
  { filename: 'ecolodge.js', exported: i4 },
  { filename: 'event.js', exported: i5 },
  { filename: 'gallery.js', exported: i6 },
  { filename: 'home.js', exported: i7 },
  { filename: 'index.js', exported: i8 },
  { filename: 'location.js', exported: i9 },
  { filename: 'mission.js', exported: i10 },
  { filename: 'partners.js', exported: i11 },
  { filename: 'projects.js', exported: i12 },
  { filename: 'resources.js', exported: i13 },
  { filename: 'spreadtheword.js', exported: i14 },
  { filename: 'team.js', exported: i15 },
  { filename: 'trustees.js', exported: i16 },
  { filename: 'us.js', exported: i17 },
  { filename: 'volunteering.js', exported: i18 },
]
